global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'spring'
    scrape_interval: 5s
    metrics_path defaults to 'application/prometheus'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:8080']
